server:
  port: 20000

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      force: true
      charset: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://huhuiyu.cn:3306/code_build_demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: test
    password: User4-test
    hikari:
      connection-test-query: select 1
      max-lifetime: 60000
mybatis:
  config-location: classpath:mybatis-config.xml
pagehelper:
  reasonable: true
swagger-enable: true